#
# Copyright 2024, Colias Group, LLC
#
# SPDX-License-Identifier: BSD-2-Clause
#

[book]
title = "Using Rust in seL4 Userspace"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
multilingual = false
src = "src"

[build]
build-dir = "build"

[preprocessor.sel4-rust-training]
before = [ "links" ]

[output.html]
additional-css = ["preprocessor/assets/sel4-rust-training.css"]
additional-js = ["preprocessor/assets/sel4-rust-training.js"]
git-repository-url = "https://github.com/coliasgroup/coliasgroup/seL4-summit-2024-rust-training"
